TeamTreas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib import admin

from Treas import views


urlpatterns = [
    path('',TemplateView.as_view(template_name="index.html"), name='index'),
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('allauth.urls')),
    path('', include('sendemail.urls')),
    path('about/',TemplateView.as_view(template_name="about.html"), name='about'),
    path('Treas/',include("Treas.urls", namespace="Treas")),
    path('logout', views.user_logout, name='logout'),
    path('login',TemplateView.as_view(template_name='login.html'),name='login'),
    path('profile/', include('customer_profile.urls')),
    path('explore/', include('explore.urls'))

]

Treas/urls.py
from django.urls import path
from Treas import views
from django.views.generic import TemplateView

app_name = 'Treas'

urlpatterns = [

]

customer_profile/urls.py
from django.urls import path
from . import views


urlpatterns = [
  path('', views.index)
]

explore/urls.py
from django.urls import path
from . import views


urlpatterns = [
  path('', views.index)
]

sendemail/urls.py
from django.contrib import admin
from django.urls import path

from .views import contactView, successView


app_name = 'mail'

urlpatterns = [
    path('contact/', contactView, name='contact'),
    path('success/', successView, name='success'),
]

Treas/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


from django.contrib import admin 
from django.contrib.auth.models import User 
from django.db import models 

customer_profile/models.py
from django.db import models

# Create your models here.
class ServiceProvider(models.Model):
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=255)
    location = models.CharField(max_length=255, default='None')
    services = models.CharField(max_length= 3000)
    products = models.CharField(max_length= 3000, default='None')

    logo = models.ImageField(default='None')


class Commerce(models.Model):
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=255)
    location = models.CharField(max_length=255, default='None')
    services = models.CharField(max_length= 3000)
    products = models.CharField(max_length= 3000, default='None')

    logo = models.ImageField(default='None')

explore/models.py
from django.db import models

# Create your models here.
class Business(models.Model):
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=255)
    location = models.CharField(max_length=255, default='None')
    image_url = models.CharField(max_length=2083, default='None')

sendemail/models.py
from django.db import models

# Create your models here.

Treas/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.models import User

    

sendemail/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.models import User

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    sender = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)
    

Treas/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, login, authenticate

from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView,FormView)

from django.contrib.auth.mixins import LoginRequiredMixin


@login_required
def user_logout(request):
    logout(request)
    return redirect('/')

customer_profile/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    # use save to add save a new business
    return render(request, 'basic.html')

explore/views.py
from django.shortcuts import render

# Create your views here.
from explore.models import Business


def index(request):
    # use save to add save a new business
    options = Business.objects.all()
    return render(request, 'index_explore.html', {'options': options})

sendemail/views.py
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from .forms import ContactForm

def contactView(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            sender = form.cleaned_data['sender']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, sender, ['admin@example.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('mail:success')
    return render(request, "email.html", {'form': form})

def successView(request):
    return HttpResponse('Success! Thank you for your message.')

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content%}
<div class="container">
    <br>
    <br>
    <h1>This is where we will say what our project is about </h1>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
{% load static %}
{% load socialaccount %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- bootstap -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <!-- font -->
  <link href="https://fonts.googleapis.com/css2?family=Merienda&display=swap" rel="stylesheet">
  <!-- animate css wat nie werk vir een of ander rede nie...-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.0/animate.min.css">
  <!-- our css -->
  <link rel="stylesheet" href="../static/Treas/css/style.css"> 

    <title>Base</title>
    <!-- add block title thing -->
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}">TeamTreas</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about' %}">About</a>
          </li>
          {% if user.is_authenticated %}       
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}" >Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class='nav-link' href="{% url 'login' %}">Login<span class="glyphicon glyphicon-user"></span>
            </a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mail:contact' %}">Contact us</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <br><br>
{% block content%}
{% endblock content %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

templates/basic.html
{% extends 'base.html' %}

{% block content %}

<div class="container" id="basic_container">
    
    <br><hr>
    <h3 id="register_heading">Register your business here</h3>
    <hr>

    <form>
    
        <div class="form-group">
            <label for="businessName">Business Name</label>
            <input type="text" class="form-control" id="businessName" placeholder="eg Village Shop">
          </div>

      
        <div class="form-group">
        <label for="businessType">Province</label>
        <select id="businessType" class="form-control">
            <option selected>Choose...</option>
            <option>Service Provider</option>
            <option>Commerce</option>
        </select>


        <div class="form-group">
          <label for="inputAddress">Address</label>
          <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
        </div>
        <div class="form-group">
          <label for="inputAddress2">Address 2</label>
          <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
        </div>
        <div class="form-row">
          <div class="form-group col-md-6">
            <label for="inputCity">City</label>
            <input type="text" class="form-control" id="inputCity">
          </div>
          <div class="form-group col-md-4">
            <label for="inputProvince">Province</label>
            <select id="inputProvince" class="form-control">
              <option selected>Choose...</option>
              <option>Eastern Cape</option>
              <option>Free State</option>
              <option>Gauteng</option>
              <option>KwaZulu-Natal</option>
              <option>Limpopo </option>
              <option>Mpumalanga</option>
              <option>Northern Cape</option>
              <option>North West</option>
              <option>Western Cape</option>

            </select>

          </div>
          <div class="form-group col-md-2">
            <label for="inputPostalCode" class="control">Postal Code</label>
            <input type="text" class="form-control" id="inputPostalCode">
          </div>
        </div>
        
        <button type="submit" class="btn btn-primary">Register Me</button>
      </form>
</div>
{% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content%}
<div class="container">
    <br>
    <br>
    <h1>Contact Us</h1>
    <br>
    <h5>Get in touch with us through the following channels</h5>
    <button class="btn btn-primary"><a style="color: white;" href="">General enquiry</a></button>
    <button class="btn btn-primary"><a style="color: white;" href="">Sales enquiry</a></button>
    <button class="btn btn-primary"><a style="color: white;" href="">Media enquiry</a></button>
    <br><br>
    <form>
        {% csrf_token %}
        {{form|crispy}}
    <input type="submit" value="submit">
    </form>

</div>
{% endblock content %}

templates/email.html
{% extends 'base.html' %}


{% load static %}
{% load socialaccount %}
{% load crispy_forms_tags %}


{% block content%}
<h1>Contact Us</h1>
<form method="POST">
    {% csrf_token %}
    {{ form | crispy}}
    <div class="form-actions">
      <button type="submit">Send</button>
    </div>
</form>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content%}

<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="../static/Treas/images/Thunder.jpg" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5 class=" animate__bounceInRight" style="animation-delay: 1s">THUNDER</h5>
          <p class=" animate__bounceInLeft" style="animation-delay: 2s">be bold move fast</p>
          <p  class=" animate__bounceInRight" style="animation-delay: 3s"><a href="#">More Info</a></p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="../static/Treas/images/solar.jpg" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5  class=" animate__slideInDown" style="animation-delay: 1s">SOLAR</h5>
          <p class=" animate__fadeInUp" style="animation-delay: 2s">one percent of the journey is finsished</p>
          <p  class=" animate__zoomIn" style="animation-delay: 3s" ><a href="#">More Info</a></p>
        </div>
      </div>
      <div class="carousel-item">
        <img src="../static/Treas/images/crypto.jpg" class="d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">
          <h5  class=" animate__zoomIn" style="animation-delay: 1s" >CRYPTO</h5>
          <p  class=" animate__fadeInUp" style="animation-delay: 2s" >one percent of the journey is finsished</p>
          <p  class=" animate__zoomIn" style="animation-delay: 3s"><a href="#">More Info</a></p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  
{% endblock content %}

templates/index_explore.html
{% extends 'base.html' %}

{% block content %}

<div id="explore">
    <div class="container">

        <h1>Explore Businesses</h2>
        <hr>

        <div>
        <div class="row">
            {% for business in options %}
            <div class="col">
                <div class="card text-white bg-dark mb-3" style="width: 18rem;">
                    <div class="card-body">
                     <h5 class="card-title">{{business.name}}</h5>
                        <p class="card-text">{{business.type}}</p>
                    <a href="#" class="btn btn-primary">View Business</a>
                    </div>
                </div>
            </div>
            {% endfor %}   
        </div>
    
    </div>       
        
    </div>

</div>


{% endblock %}

templates/login.html
{% extends 'base.html' %}

<!-- Still need to add the head block for the html files which handles the title of the page -->

{% load static %}
{% load socialaccount %}


{% block content%}
<div class="container">
    <h2>Login using one of these social applications:</h2>
    <button class="btn btn-danger"><a href="{% provider_login_url 'google' %}" style="color: white;">Login with google</a></button>
</div>
{% endblock content %}